#!/usr/bin/env bash

rm -r -f ~/ordoBudgetWin

mkdir ~/ordoBudgetWin

# Loop through arguments
for arg in "$@"; do
   case "$arg" in
      spreadSheetId=*) spreadSheetId="${arg#*=}" ;;
      sheetId=*) sheetId="${arg#*=}" ;;
   esac
done

if [[ -z "$spreadSheetId" ]]; then 
  echo "spreadSheetId is empty"

elif [[ -z "$sheetId" ]]; then 
  echo "sheetId is empty"

else
  GOOS=windows GOARCH=amd64 go build -ldflags "-X 'budgetAutomation/internal/request.SpreadSheetId=${spreadSheetId}' -X 'budgetAutomation/internal/request.BudgetSheetId=${sheetId}'" -o ~/ordoBudget/ordoBudget.exe cmd/cli/cli.go

fi



