#!/usr/bin/env bash

rm -f ~/ordoBudgetWin/ordoBudget.exe

mkdir -p ~/ordoBudgetWin

# Loop through arguments
# Loop through arguments
for arg in "$@"; do
   case "$arg" in
      spreadSheetId=*) spreadSheetId="${arg#*=}" ;;
      sheetId=*) sheetId="${arg#*=}" ;;
      multipleUsers=*) multipleUsers="${arg#*=}";;
   esac
done

if [[ -z "$spreadSheetId" ]]; then 
  echo "spreadSheetId is empty"
elif [[ -z "$sheetId" ]]; then 
  echo "sheetId is empty"
elif [[ -z "$multipleUsers" ]]; then 
  echo "multipleUsers is empty"

else
  GOOS=windows GOARCH=amd64 go build -ldflags "-X 'OrdoBudget/internal/request.SpreadSheetId=${spreadSheetId}' -X 'OrdoBudget/internal/request.BudgetSheetId=${sheetId}' -X 'Ordobudget/cmd/cli.multipleUsers=${multipleUsers}'" -o ~/ordoBudgetWin/ordoBudget.exe cmd/cli/cli.go

fi



