#!/usr/bin/env bash

rm -f ~/ordoBudget/ordoBudget

mkdir -p ~/ordoBudget

# Loop through arguments
for arg in "$@"; do
   case "$arg" in
      spreadSheetId=*) spreadSheetId="${arg#*=}" ;;
      sheetId=*) sheetId="${arg#*=}" ;;
      multipleUsers=*) multipleUsers="${arg#*=}";;
   esac
done

if [[ -z "$spreadSheetId" ]]; then 
  echo "spreadSheetId is empty"
elif [[ -z "$sheetId" ]]; then 
  echo "sheetId is empty"
elif [[ -z "$multipleUsers" ]]; then 
  echo "multipleUsers is empty"

else
  go build -ldflags "-X 'OrdoBudget/internal/request.SpreadSheetId=${spreadSheetId}' -X 'OrdoBudget/internal/request.BudgetSheetId=${sheetId}' -X 'Ordobudget/cmd/cli.multipleUsers=${multipleUsers}'" -o ~/ordoBudget/ordoBudget cmd/cli/cli.go

fi




